[colors]
surface_global      = "#0b0e14"
surface_active      = "#131721"
surface_inactive    = "#0b0e14"
surface_error       = "#f07178"

text_primary        = "#bfbdb6"
text_secondary      = "#e6b450"
text_secondary_in   = "#a07d33"
text_selection      = "#0b0e14"
text_muted          = "#565b66"

border_active       = "#ffb454"
border_inactive     = "#2a2f3a"

accent              = "#ffb454"
accent_inactive     = "#a87838"

[borders]
display             = true
style               = "rounded"

[progress]
color               = ["#ffb454", "#f29668", "#f07178"]
speed               = 6

[progress.bar]
# color               = "#ffb454"
symbol_played       = "▰"
symbol_unplayed     = "▱"

[progress.spectrum]
decay               = 0.85

[extras]
decorator           = "◆"
